### ISSUE TITLE
Fix delay slider

### ISSUE THREAD

**Issue by rwos** [rwos/gifstopmotion#1]
currently only changes the delay for the next frame
should trigger a re-encode with the new delay of all frames

**Comment by glaubinix** [comment]
should work with https://github.com/rwos/gifstopmotion/pull/15 but needs https://github.com/rwos/gifstopmotion/issues/16 to look somewhat ok

**Comment by rwos** [comment]
@glaubinix yup, I'm currently in the middle of a ~~complete rewrite~~ ~~tiny cleanup~~ refactoring. That will have more space for controls, including the slider (which does already work).

**Comment by rwos** [comment]
done
